//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow booked at time.
        /// </summary>
        internal static string allowBookedAtTime {
            get {
                return ResourceManager.GetString("allowBookedAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit Apartment Design.
        /// </summary>
        internal static string AparmentOptionDesign {
            get {
                return ResourceManager.GetString("AparmentOptionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string ApproveButton {
            get {
                return ResourceManager.GetString("ApproveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of posts.
        /// </summary>
        internal static string ArticleCount {
            get {
                return ResourceManager.GetString("ArticleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author List.
        /// </summary>
        internal static string AuthorList {
            get {
                return ResourceManager.GetString("AuthorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balcony.
        /// </summary>
        internal static string balcony {
            get {
                return ResourceManager.GetString("balcony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Furniture.
        /// </summary>
        internal static string basicFurniture {
            get {
                return ResourceManager.GetString("basicFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ContentTab {
            get {
                return ResourceManager.GetString("ContentTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Tab.
        /// </summary>
        internal static string ContentTab1 {
            get {
                return ResourceManager.GetString("ContentTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book.
        /// </summary>
        internal static string CreateBookButton {
            get {
                return ResourceManager.GetString("CreateBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Article.
        /// </summary>
        internal static string CreateNewButton {
            get {
                return ResourceManager.GetString("CreateNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Min Deposit Amount.
        /// </summary>
        internal static string CustomMinDepositAmount {
            get {
                return ResourceManager.GetString("CustomMinDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Post.
        /// </summary>
        internal static string DateOfPost {
            get {
                return ResourceManager.GetString("DateOfPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Article.
        /// </summary>
        internal static string DeleteArticleButton {
            get {
                return ResourceManager.GetString("DeleteArticleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Book.
        /// </summary>
        internal static string DeleteBookButton {
            get {
                return ResourceManager.GetString("DeleteBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton1 {
            get {
                return ResourceManager.GetString("DeleteButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to detele selected item(s) ?.
        /// </summary>
        internal static string DeleteMultiWarning {
            get {
                return ResourceManager.GetString("DeleteMultiWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction kitchen.
        /// </summary>
        internal static string directionKitchen {
            get {
                return ResourceManager.GetString("directionKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to drafts.
        /// </summary>
        internal static string DraftsButton {
            get {
                return ResourceManager.GetString("DraftsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLink {
            get {
                return ResourceManager.GetString("EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditUpdateButton {
            get {
                return ResourceManager.GetString("EditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for rent.
        /// </summary>
        internal static string forRentStatus {
            get {
                return ResourceManager.GetString("forRentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Apartment Price.
        /// </summary>
        internal static string hideApartmentPrice {
            get {
                return ResourceManager.GetString("hideApartmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image Selected.
        /// </summary>
        internal static string ImageDeleteSelectedButton {
            get {
                return ResourceManager.GetString("ImageDeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (select).
        /// </summary>
        internal static string ImageDeleteSelectedButton1 {
            get {
                return ResourceManager.GetString("ImageDeleteSelectedButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Image.
        /// </summary>
        internal static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File.
        /// </summary>
        internal static string ImageFile1 {
            get {
                return ResourceManager.GetString("ImageFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        internal static string ImageTitleLabel {
            get {
                return ResourceManager.GetString("ImageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Image.
        /// </summary>
        internal static string ImageUpdateButton {
            get {
                return ResourceManager.GetString("ImageUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string IsDelected {
            get {
                return ResourceManager.GetString("IsDelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        internal static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string lblfurniture {
            get {
                return ResourceManager.GetString("lblfurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Deposit Amount.
        /// </summary>
        internal static string MinDepositAmount {
            get {
                return ResourceManager.GetString("MinDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        internal static string NewsEditImageTitleLabel {
            get {
                return ResourceManager.GetString("NewsEditImageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewsName {
            get {
                return ResourceManager.GetString("NewsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New categories.
        /// </summary>
        internal static string NewsTypeList {
            get {
                return ResourceManager.GetString("NewsTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit New Categories.
        /// </summary>
        internal static string NewsTypeOption {
            get {
                return ResourceManager.GetString("NewsTypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD/Edit New Type.
        /// </summary>
        internal static string NewTypeEdit {
            get {
                return ResourceManager.GetString("NewTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approved your article  .
        /// </summary>
        internal static string NotifyApproval {
            get {
                return ResourceManager.GetString("NotifyApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented on  your article .
        /// </summary>
        internal static string NotifyComment {
            get {
                return ResourceManager.GetString("NotifyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked your article .
        /// </summary>
        internal static string NotifyLike {
            get {
                return ResourceManager.GetString("NotifyLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared your article .
        /// </summary>
        internal static string NotifyShare {
            get {
                return ResourceManager.GetString("NotifyShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string PostButton {
            get {
                return ResourceManager.GetString("PostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Gratitude.
        /// </summary>
        internal static string PostGratitude {
            get {
                return ResourceManager.GetString("PostGratitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Successfully.
        /// </summary>
        internal static string PostSuccessMessage {
            get {
                return ResourceManager.GetString("PostSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ReviewButton {
            get {
                return ResourceManager.GetString("ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale type.
        /// </summary>
        internal static string saleType {
            get {
                return ResourceManager.GetString("saleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        internal static string segment {
            get {
                return ResourceManager.GetString("segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select category !.
        /// </summary>
        internal static string SelectTypeMessage {
            get {
                return ResourceManager.GetString("SelectTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string ThumbnailLabel {
            get {
                return ResourceManager.GetString("ThumbnailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        internal static string TimeAgoDay {
            get {
                return ResourceManager.GetString("TimeAgoDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string TimeAgoDaysFormat {
            get {
                return ResourceManager.GetString("TimeAgoDaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        internal static string TimeAgoHour {
            get {
                return ResourceManager.GetString("TimeAgoHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string TimeAgoHoursFormat {
            get {
                return ResourceManager.GetString("TimeAgoHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        internal static string TimeAgoMinute {
            get {
                return ResourceManager.GetString("TimeAgoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string TimeAgoMinutesFormat {
            get {
                return ResourceManager.GetString("TimeAgoMinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        internal static string TimeAgoMonth {
            get {
                return ResourceManager.GetString("TimeAgoMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string TimeAgoMonthsFormat {
            get {
                return ResourceManager.GetString("TimeAgoMonthsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second ago.
        /// </summary>
        internal static string TimeAgoSecond {
            get {
                return ResourceManager.GetString("TimeAgoSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        internal static string TimeAgoSecondsFormat {
            get {
                return ResourceManager.GetString("TimeAgoSecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year ago.
        /// </summary>
        internal static string TimeAgoYear {
            get {
                return ResourceManager.GetString("TimeAgoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        internal static string TimeAgoYearsFormat {
            get {
                return ResourceManager.GetString("TimeAgoYearsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfully.
        /// </summary>
        internal static string UpdateAuthorSuccess {
            get {
                return ResourceManager.GetString("UpdateAuthorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
